# Generated by Django 3.2.9 on 2022-03-05 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20220305_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='posts',
            name='image',
            field=models.URLField(),
        ),
    ]
