# Generated by Django 3.2.9 on 2022-04-12 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='blog',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_blog', to='main.blog'),
        ),
    ]
