# Generated by Django 3.2.9 on 2022-04-24 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_profile_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.URLField(max_length=300),
        ),
        migrations.AlterField(
            model_name='posts',
            name='image',
            field=models.URLField(max_length=300),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.URLField(max_length=300),
        ),
    ]
